In [1]:
import numpy as np
ALIGMENT = 50

In [2]:
print("TASK 1".center(ALIGMENT))
arr = np.random.randint(low=0, high=10, size=30)
print(*arr)
arr, counts = np.unique(arr, return_counts=True)
arr = sorted(zip(counts, arr), reverse=True)
print(*[x for _,x in arr])

                      TASK 1                      
0 1 7 5 5 4 5 5 6 7 0 0 2 6 1 4 7 7 2 6 9 0 6 7 7 2 1 5 8 1
7 5 6 1 0 2 4 9 8


In [3]:
print("TASK 2".center(ALIGMENT))
h, w = 250,250
img = np.random.randint(low=0, high=256, dtype=np.uint8, size=(3,h,w))
img_new = np.vstack(img.transpose((1,2,0)))
print(f"Уникальных значений: {len(np.unique(img_new, axis=0))}")

                      TASK 2                      
Уникальных значений: 62367


In [4]:
print("TASK 3".center(ALIGMENT))

def average_float_vector(win_size, arr):
    res = []
    for i in range(0, len(arr)-win_size):
        res.append(arr[i:i+win_size].sum()/3)
    return res
    
win_size = 3
arr = np.random.randint(low=0, high=10, size=30)
print(arr)
print(average_float_vector(win_size, arr))

                      TASK 3                      
[9 0 2 3 2 9 2 3 1 0 1 5 5 0 9 1 2 3 8 8 4 4 8 7 0 6 6 1 5 0]
[3.6666666666666665, 1.6666666666666667, 2.3333333333333335, 4.666666666666667, 4.333333333333333, 4.666666666666667, 2.0, 1.3333333333333333, 0.6666666666666666, 2.0, 3.6666666666666665, 3.3333333333333335, 4.666666666666667, 3.3333333333333335, 4.0, 2.0, 4.333333333333333, 6.333333333333333, 6.666666666666667, 5.333333333333333, 5.333333333333333, 6.333333333333333, 5.0, 4.333333333333333, 4.0, 4.333333333333333, 4.0]


In [5]:
print("TASK 4".center(ALIGMENT))

def is_triang(arr):
    return sum(arr) - 2 * max(arr) > 0

n = int(input())
arr = np.random.randint(low=0, high=256, size=(n, 3))
triangs = zip(arr, np.apply_along_axis(is_triang, 1, arr))
print(*[f"{sides} -- {isTriang}\n" for sides, isTriang in triangs if isTriang])

                      TASK 4                      
[174 231  66] -- True
 [245 167 154] -- True
 [ 64 225 210] -- True

